export default [
    {
        id: 0,
        name: "Le monde merveilleux de Totoro",
        price: 0,
        town: "Nice",
        type: "dpp",
        date: "2019-06-15T00:05:32.000Z",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        location: "36 Rue des maisons roses, 06410 Biot",
        organizer: 0,
        participants: [1, 2],
        maxParticipantsNumber: 5,
        enrolled: -1
    },
    {
        id: 1,
        name: "Repas 2",
        price: 0,
        town: "Paris",
        type: "dpp",
        date: "2019-08-15T00:05:32.000Z",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        location: "36 Rue des maisons roses, 06410 Biot",
        organizer: 0,
        participants: [],
        maxParticipantsNumber: 4,
        enrolled: -1
    },
    {
        id: 2,
        name: "Repas 3",
        price: 0,
        town: "New-York",
        type: "dpp",
        date: "2019-10-15T00:05:32.000Z",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        location: "36 Rue des maisons roses, 06410 Biot",
        organizer: 1,
        participants: [],
        maxParticipantsNumber: 8,
        enrolled: -1
    },
    {
        id: 3,
        name: "Le monde merveilleux de Totoro",
        price: 0,
        town: "Nice",
        type: "meetic",
        date: "2019-06-15T00:05:32.000Z",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        location: "36 Rue des maisons roses, 06410 Biot",
        organizer: 0,
        participants: [1, 2],
        maxParticipantsNumber: 5,
        enrolled: -1
    },
    {
        id: 4,
        name: "Le oui",
        price: 7,
        town: "Nice",
        type: "classic",
        date: "2019-06-15T00:05:32.000Z",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        location: "36 Rue des maisons roses, 06410 Biot",
        organizer: 1,
        participants: [1, 2],
        maxParticipantsNumber: 5,
        enrolled: -1
    },
    {
        id: 5,
        name: "Voyage exotique",
        price: 5,
        town: "Nice",
        type: "meetic",
        date: "2019-06-15T00:05:32.000Z",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        location: "36 Rue des maisons roses, 06410 Biot",
        organizer: 1,
        participants: [1, 2],
        maxParticipantsNumber: 5,
        enrolled: -1
    }
];